# Configuration for the labeler workflow
# This file defines which labels to apply based on file paths changed in PRs

# GSSoC'25 Program Labels (applied to all PRs automatically by gssoc-labeler.yml)
"GSSoC'25":
  - "**/*"  # All files - indicates this is part of GSSoC'25

# Level assignment based on complexity and scope of changes
# Level1: Simple changes like documentation, minor UI tweaks, small bug fixes
"Level1":
  - "*.md"                    # Documentation updates
  - ".gitignore"              # Git configuration
  - "*.txt"                   # Text files
  - "public/images/**/*"      # Image assets only
  - "views/**/*.ejs"          # Simple view changes (single file)
  - "public/CSS/**/*"         # CSS styling changes
  - "CONTRIBUTION.md"
  - "CODE_OF_CONDUCT.md"
  - "SECURITY.md"
  - "SPARKLE_IMPROVEMENTS.md"

# Level2: Moderate complexity changes affecting functionality or multiple components
"Level2":
  - "controllers/**/*"        # Controller logic changes
  - "routes/**/*"            # Routing changes
  - "public/JS/**/*"         # JavaScript functionality
  - "views/includes/**/*"    # Shared template components
  - "utils/**/*"             # Utility functions
  - "middleware.js"          # Middleware modifications
  - "cloudConfig.js"         # Cloud configuration
  - "*.config.js"            # Configuration files
  - "*.config.json"

# Level3: Complex changes affecting core functionality, database, or architecture
"Level3":
  - "models/**/*"            # Database model changes
  - "app.js"                 # Main application file
  - "schema.js"              # Database schema
  - "init/**/*"              # Database initialization/seeding
  - "package.json"           # Dependency changes
  - "package-lock.json"      # Lock file changes
  - "**/*seed*"              # Database seeding
  - "**/*migration*"         # Database migrations
  - ".github/workflows/**/*" # CI/CD workflow changes
  - "Dockerfile"             # Container configuration
  - "docker-compose.yml"     # Docker orchestration
  - "**/*auth*"              # Authentication changes
  - "**/*security*"          # Security-related changes

# Frontend changes
"frontend":
  - "views/**/*"
  - "public/**/*"
  - "*.html"
  - "*.ejs"
  - "*.css"
  - "*.scss"
  - "*.js"
  - "public/CSS/**/*"
  - "public/JS/**/*"
  - "public/images/**/*"

# Backend changes
"backend":
  - "controllers/**/*"
  - "models/**/*"
  - "routes/**/*"
  - "middleware.js"
  - "app.js"
  - "utils/**/*"
  - "schema.js"

# Database related
"database":
  - "models/**/*"
  - "init/**/*"
  - "schema.js"
  - "**/*seed*"
  - "**/*migration*"

# Configuration changes
"config":
  - "package.json"
  - "package-lock.json"
  - "*.env*"
  - ".env.example"
  - "cloudConfig.js"
  - "*.config.js"
  - "*.config.json"

# Documentation
"documentation":
  - "README.md"
  - "*.md"
  - "docs/**/*"
  - "CONTRIBUTION.md"
  - "CODE_OF_CONDUCT.md"
  - "SECURITY.md"
  - "SPARKLE_IMPROVEMENTS.md"

# CI/CD and DevOps
"ci/cd":
  - ".github/**/*"
  - "Dockerfile"
  - "docker-compose.yml"
  - ".dockerignore"
  - "*.yml"
  - "*.yaml"

# Dependencies
"dependencies":
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"

# Testing
"testing":
  - "test/**/*"
  - "tests/**/*"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "jest.config.js"
  - "cypress.json"
  - "cypress/**/*"

# Security
"security":
  - "SECURITY.md"
  - "middleware.js"
  - "**/*auth*"
  - "**/*security*"

# UI/UX
"ui/ux":
  - "views/**/*"
  - "public/CSS/**/*"
  - "public/images/**/*"
  - "**/*style*"
  - "**/*theme*"

# API changes
"api":
  - "routes/**/*"
  - "controllers/**/*"
  - "**/*api*"

# Performance
"performance":
  - "**/*perf*"
  - "**/*performance*"
  - "**/*optimize*"
  - "**/*cache*"

# Small changes (usually safe to merge) - automatically gets Level1
"minor":
  - "*.md"
  - ".gitignore" 
  - "*.txt"

# Additional Level3 indicators for complex changes
"Level3":
  - "**/*test*"              # Test file changes (comprehensive testing)
  - "jest.config.js"         # Testing configuration
  - "cypress.json"           # End-to-end testing
  - "cypress/**/*"           # Cypress test files